# @package _group_
module: image_classification.datasets.fashion_mnist
class_name: FashionMNIST
download: False
test_preprocessor: basic
train_preprocessor: basic
train_eval_split: 50000
batch_size: 64